apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.port }}
      name: {{ .Values.app.name }}
  selector:
    app: {{ .Values.app.labels }}
  type: {{ .Values.app.service.type }}
