apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.env.MYSQL_ROOT_PASSWORD | b64enc }}
  MYSQL_DATABASE: {{ .Values.db.env.MYSQL_DATABASE | b64enc }}
  SPRING_DATASOURCE_PASSWORD:
    {{ .Values.app.env.SPRING_DATASOURCE_PASSWORD | b64enc }}
  SPRING_DATASOURCE_USERNAME:
    {{ .Values.app.env.SPRING_DATASOURCE_USERNAME | b64enc }}
