apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: {{ .Values.db.labels }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
