name: ci-pipeline

on:
  push:
    branches:
     - main
     - feature/*

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin

      - name: Build with Maven
        run: mvn clean install -DskipTests

#mvn verify is not working with existing code
  # code-quality:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: "17"
  #         distribution: temurin

  #     - name: Run Code Quality Checks
  #       run: mvn verify

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/feature/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/devops-challenge:latest .

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 \
            -t ${{ secrets.DOCKER_USERNAME }}/devops-challenge:latest --push .
